stages:
  - build
  - clippy
  - fmt 

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  image: "rustlang/rust:nightly"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libssl-dev libsodium-dev libopus-dev pkg-config
    - cargo --version
    - rustc --version
  stage: build
  script:
    - cargo build --release
  cache:
    untracked: true
    paths:
      - target/
      - cargo/
  artifacts:
    paths:
      - target/release/arc_bot
    expire_in: 5 day

clippy:
  image: "rustlang/rust:nightly"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libssl-dev libsodium-dev libopus-dev pkg-config
    - cargo --version
    - rustc --version
  stage: clippy
  script:
    - cargo clippy
  cache:
    untracked: true
    paths:
      - target/
      - cargo/

fmt:
  image: "rustlang/rust:nightly"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libssl-dev libsodium-dev libopus-dev pkg-config
    - cargo --version
    - rustc --version
  stage: fmt
  script:
    - cargo fmt
