[package]
name = "arc_bot"
version = "0.0.4"
authors = ["nitsuga5124 <nitsuga5124@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
toml = "0.5.6"
postgres = "0.17.1"

[dependencies.serenity]
version = "0.8"
default-features = false
features = ["builder", "cache", "client", "framework", "gateway", "http", "model", "standard_framework", "utils", "native_tls_backend", "voice", "absolute_ratelimits"]


[dependencies.reqwest]
version = "0.10.1"
features = ["blocking", "json"]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dependencies.quick-xml]
version = "0.17.2"
features = ["serialize"]
