[package]
name = "discord_bot"
version = "0.0.2"
authors = ["nitsuga5124 <nitsuga5124@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
rand = "0.7.3"
#serde_json = "1.0.46"

[dependencies.reqwest]
version = "0.10.1"
features = ["blocking", "json"]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

